<div class="alert alert-block alert-success" style="font-family: Times New Roman">
    <h4><strong>Laboratory Task 5</strong></h4>

**1. Perform Standard Imports**

<br>

**2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.**

<br>

**3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use `42` as the seed parameter.**

<br>

**4. Create a tensor "x" from the array above**

<br>

**5. Change the dtype of x from `int32` to `int64`**

<br>

**6. Reshape `x` into a 3x2 tensor** <br> There are several ways to do this.

<br>

**7. Return the right-hand column of tensor `x`**

<br>

**8. Without changing x, return a tensor of square values of `x`** <br> There are several ways to do this.

<br>

**9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`** <br> Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. <br> Think about what shape it should have to permit matrix multiplication.

<br>

**10. Find the matrix product of `x` and `y`.**

</div>

<h4 style="font-family: Times New Roman"><strong>1. Standard Imports</strong></h4>

In [1]:
import torch
import numpy as np

<h4 style="font-family: Times New Roman"><strong>2. Seed-Setting Function</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
Random number generation in NumPy and in PyTorch are handled separately, each with its own generator and its
own seed. Since this task uses random values from both libraries, <tt>set_seed()</tt> sets both
<tt>np.random.seed()</tt> and <tt>torch.manual_seed()</tt> so that calling it once is enough to make every
random value below reproducible, regardless of which library generated it. It has no return value, per the
instructions &mdash; its only job is the side effect of fixing the seed.
</p>

In [2]:
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

<h4 style="font-family: Times New Roman"><strong>3. Random NumPy Array</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<tt>np.random.randint(low, high, size)</tt> draws from <tt>low</tt> (inclusive) up to <tt>high</tt> (exclusive),
which matches the "0 (inclusive) and 5 (exclusive)" wording of the instructions. The dtype is set to
<tt>int32</tt> on purpose here &mdash; step 5 asks to change the tensor's dtype from <tt>int32</tt> to
<tt>int64</tt> later, and that only makes sense to demonstrate if the array (and the tensor made from it) is
actually <tt>int32</tt> to begin with.
</p>

In [3]:
set_seed(42)
arr = np.random.randint(0, 5, 6, dtype=np.int32)
print(arr)
print(arr.dtype)

[3 4 2 4 4 1]
int32


<h4 style="font-family: Times New Roman"><strong>4. Tensor from the NumPy Array</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<tt>torch.from_numpy()</tt> wraps the existing array without copying it, and it carries the array's dtype over
&mdash; so <tt>x</tt> starts out as an <tt>int32</tt> tensor, matching <tt>arr</tt>.
</p>

In [4]:
x = torch.from_numpy(arr)
print(x)
print(x.dtype)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)
torch.int32


<h4 style="font-family: Times New Roman"><strong>5. Changing the dtype</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
As the notebook's earlier section on dtypes points out, <tt>x = torch.tensor(x, dtype=torch.type)</tt> is the
wrong way to do this &mdash; it triggers a tensor-cloning warning. The correct approach is the <tt>.type()</tt>
method, which returns a new tensor cast to the requested dtype.
</p>

In [5]:
x = x.type(torch.int64)
print(x)
print(x.dtype)

tensor([3, 4, 2, 4, 4, 1])
torch.int64


<h4 style="font-family: Times New Roman"><strong>6. Reshaping into 3&times;2</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<tt>x</tt> has 6 elements, so it can be reshaped into any shape whose dimensions multiply to 6 &mdash; 3 rows by
2 columns in this case. Either <tt>.view()</tt> or <tt>.reshape()</tt> works here since <tt>x</tt> is
contiguous in memory; <tt>.reshape()</tt> is used below since it also falls back gracefully to making a copy on
tensors where <tt>.view()</tt> would raise an error.
</p>

In [6]:
x = x.reshape(3, 2)
print(x)
print(x.shape)

tensor([[3, 4],
        [2, 4],
        [4, 1]])
torch.Size([3, 2])


<h4 style="font-family: Times New Roman"><strong>7. Right-Hand Column</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
Standard NumPy-style slicing carries over to tensors: <tt>x[:, 1]</tt> takes every row and column index 1,
which is the second (right-hand) column.
</p>

In [7]:
right_col = x[:, 1]
print(right_col)

tensor([4, 4, 1])


<h4 style="font-family: Times New Roman"><strong>8. Squared Values, Without Changing <tt>x</tt></strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<tt>x.pow(2)</tt> (equivalently <tt>x ** 2</tt> or <tt>torch.square(x)</tt>) returns a new tensor and leaves
<tt>x</tt> untouched. The in-place version, <tt>x.pow_(2)</tt>, would overwrite <tt>x</tt>, which is exactly
what the instructions say not to do &mdash; printing <tt>x</tt> again afterward confirms it is still the
original 3&times;2 tensor.
</p>

In [8]:
x_squared = x.pow(2)
print("Squared:")
print(x_squared)

print("\nx is unchanged:")
print(x)

Squared:
tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

x is unchanged:
tensor([[3, 4],
        [2, 4],
        [4, 1]])


<h4 style="font-family: Times New Roman"><strong>9. Building <tt>y</tt> for Matrix Multiplication</strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
<tt>x</tt> is (3, 2). For <tt>x @ y</tt> to be valid, <tt>y</tt>'s first dimension has to match <tt>x</tt>'s
second dimension, i.e. 2 rows. The instructions also ask for the same number of elements as <tt>x</tt>, which
is 6, so <tt>y</tt> has to be (2, 3): 2 rows to satisfy matrix multiplication, times 3 columns to reach 6
elements. <tt>torch.randint(low, high, size)</tt> is the PyTorch equivalent of the NumPy call used for
<tt>arr</tt> earlier, and the seed is reset to 42 right before it so this cell produces the same values on
every run.
</p>

In [9]:
set_seed(42)
y = torch.randint(0, 5, (2, 3))
print(y)
print(y.shape)

tensor([[2, 2, 1],
        [4, 1, 0]])
torch.Size([2, 3])


<h4 style="font-family: Times New Roman"><strong>10. Matrix Product of <tt>x</tt> and <tt>y</tt></strong></h4>

<p style="font-family:Times New Roman; text-align:justify; font-size:15px">
With <tt>x</tt> at (3, 2) and <tt>y</tt> at (2, 3), <tt>torch.mm(x, y)</tt> (equivalently <tt>x @ y</tt> or
<tt>x.mm(y)</tt>) produces a (3, 3) result, following the same rule covered earlier in the notebook: an
(a, b) tensor times a (b, c) tensor gives an (a, c) tensor.
</p>

In [10]:
product = torch.mm(x, y)
print(product)
print(product.shape)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
torch.Size([3, 3])
